### ISSUE TITLE
SDK doesn't support proxy configuration

### ISSUE THREAD

**Issue by rgf2004** [amzn/amazon-pay-api-sdk-java#1]
the current implementation of the SDK doesn't support proxy configuration same as old version fo AmazonPay SDK https://github.com/amzn/amazon-pay-sdk-java/blob/9b0bf0ff293dd24585aabf8e25b01d016e6620d8/src/com/amazon/pay/impl/PayConfig.java#L36

**Comment by shangamesh** [comment]
Proxy is enabled from Version 2.3.0. Please check
