### ISSUE TITLE
Breaking change - new json lib

### ISSUE THREAD

**Issue by 0x54321** [amzn/amazon-pay-api-sdk-java#13]
The recent switch of the json handling library from "net.sf.json" to "org.json" has broken my build.

Since this is a breaking change, it should **not** be done in a minor version.

Related: https://github.com/amzn/amazon-pay-api-sdk-java/issues/5

**Comment by shangamesh** [comment]
Apologies for the breaking changes. We got security risks for using old libraries which was not containing any latest version after 2010. Hence we were strongly recommended to upgrade to alternative library by our internal security team. We are upgraded major version from 2.3.4 to 2.4.0. All the Amazon pay SDK are maintained under version 2.X.Y, whenever there is a breaking we will upgrade X in the verison
