### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [amzn/amazon-pay-api-sdk-java#2]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by bjguillot** [comment]
According to the links above 1.65 is the most recent version, and our pom.xml file has:
```xml
           <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.65</version>
```
So it seems we already are using the latest version.  Is there something else you see in our version selection that looks like it needs updating?

**Comment by Neustradamus** [comment]
@bjguillot: Like I see, it has been done the same day that I have done this ticket :)

Amazon Pay API SDK (Java) 2.0.0:
- https://github.com/amzn/amazon-pay-api-sdk-java/commit/5f9572b99a9e1dd7ecbd6d166f1cbbe065d33713#diff-600376dffeb79835ede4a0b285078036

**Comment by bjguillot** [comment]
Ah, ok, looks like it your message came in while our changes were already inflight.  So I can go ahead and close the ticket.  Thinks @Neustradamus for keeping an eye out.

**Comment by Neustradamus** [comment]
@bjguillot: Can you update to 1.69?
