### ISSUE TITLE
Remove plugins from dependencies

### ISSUE THREAD

**Issue by rougou** [amzn/amazon-pay-api-sdk-java#3]
Hi, I couldn't build or use this SDK because nexus-staging-maven-plugin depends on this [library](https://mvnrepository.com/artifact/commons-beanutils/commons-beanutils-core/1.8.3-SONATYPE) which isn't in maven central.

If you remove the plugins from dependencies, the problem is fixed. I think they should be in the plugins or pluginManagment section, anyway. Please remove the following from dependencies and put in the proper sections if necessary:
https://github.com/amzn/amazon-pay-api-sdk-java/blob/master/pom.xml#L10-L51

**Comment by bjguillot** [comment]
Hi @rougou, the recent 2.2.0 release from this week removed the lines that you identified from pom.xml.  Take a look at let us know if this addresses your issue.

https://github.com/amzn/amazon-pay-api-sdk-java/releases/tag/2.2.0

**Comment by rougou** [comment]
Thanks @bjguillot, didn't notice the release!
